name: Build and publish snapshot

on:
  push:
    paths-ignore:
      - 'docs'

jobs:
  publish:
    name: Publish `-SNAPSHOT` artifact to Sleeping Town maven
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref_name == 'main')
    environment: publishing
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Publish with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: clean build publish --info --stacktrace -PsleepingUsername=${{secrets.SLEEPING_USERNAME}} -PsleepingPassword=${{secrets.SLEEPING_PASSWORD}} -PversionSuffix=SNAPSHOT
